spring.datasource.url=jdbc:mysql://localhost:3306/lab_equipment_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=achu2006

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

server.port=8080
